version: 2.1
jobs:
  build:
    working_directory: ~/rent_mall-frontend
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: npm-update
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "./rent_mall-frontend/package-lock.json" }}
      - run:
          name: npm-install
          command: |
            cd rent_mall-frontend
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "./rent_mall-frontend/package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: |
            cd rent_mall-frontend
            npm test
